package com.atemukesu.extendednoteblock.map;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Collectors;

public final class InstrumentMap {
    public static final Map<String, Integer> BLOCK_TO_GM_INSTRUMENT;
    public static final Map<Integer, String> GM_INSTRUMENT_TO_BLOCK;
    static {
        Map<String, Integer> blockIndexMap = new HashMap<>();
        blockIndexMap.put("minecraft:dirt", 0);
        blockIndexMap.put("minecraft:coarse_dirt", 1);
        blockIndexMap.put("minecraft:podzol", 2);
        blockIndexMap.put("minecraft:rooted_dirt", 3);
        blockIndexMap.put("minecraft:clay", 4);
        blockIndexMap.put("minecraft:terracotta", 5);
        blockIndexMap.put("minecraft:moss_block", 6);
        blockIndexMap.put("minecraft:red_nether_bricks", 7);
        blockIndexMap.put("minecraft:light_blue_concrete", 8);
        blockIndexMap.put("minecraft:polished_diorite", 9);
        blockIndexMap.put("minecraft:amethyst_block", 10);
        blockIndexMap.put("minecraft:iron_block", 11);
        blockIndexMap.put("minecraft:oak_planks", 12);
        blockIndexMap.put("minecraft:bone_block", 13);
        blockIndexMap.put("minecraft:gold_block", 14);
        blockIndexMap.put("minecraft:hay_block", 15);
        blockIndexMap.put("minecraft:beehive", 16);
        blockIndexMap.put("minecraft:dried_kelp_block", 17);
        blockIndexMap.put("minecraft:netherrack", 18);
        blockIndexMap.put("minecraft:quartz_block", 19);
        blockIndexMap.put("minecraft:mushroom_stem", 20);
        blockIndexMap.put("minecraft:bookshelf", 21);
        blockIndexMap.put("minecraft:bricks", 22);
        blockIndexMap.put("minecraft:mud_bricks", 23);
        blockIndexMap.put("minecraft:oak_log", 24);
        blockIndexMap.put("minecraft:white_wool", 25);
        blockIndexMap.put("minecraft:shroomlight", 26);
        blockIndexMap.put("minecraft:sea_lantern", 27);
        blockIndexMap.put("minecraft:soul_sand", 28);
        blockIndexMap.put("minecraft:blackstone", 29);
        blockIndexMap.put("minecraft:obsidian", 30);
        blockIndexMap.put("minecraft:glass", 31);
        blockIndexMap.put("minecraft:oak_wood", 32);
        blockIndexMap.put("minecraft:spruce_planks", 33);
        blockIndexMap.put("minecraft:birch_planks", 34);
        blockIndexMap.put("minecraft:jungle_planks", 35);
        blockIndexMap.put("minecraft:acacia_planks", 36);
        blockIndexMap.put("minecraft:dark_oak_planks", 37);
        blockIndexMap.put("minecraft:purpur_block", 38);
        blockIndexMap.put("minecraft:purpur_pillar", 39);
        blockIndexMap.put("minecraft:cherry_planks", 40);
        blockIndexMap.put("minecraft:mangrove_planks", 41);
        blockIndexMap.put("minecraft:crimson_planks", 42);
        blockIndexMap.put("minecraft:warped_planks", 43);
        blockIndexMap.put("minecraft:chiseled_stone_bricks", 44);
        blockIndexMap.put("minecraft:melon_block", 45);
        blockIndexMap.put("minecraft:smooth_sandstone", 46);
        blockIndexMap.put("minecraft:stone", 47);
        blockIndexMap.put("minecraft:calcite", 48);
        blockIndexMap.put("minecraft:light_gray_wool", 49);
        blockIndexMap.put("minecraft:end_stone", 50);
        blockIndexMap.put("minecraft:end_stone_bricks", 51);
        blockIndexMap.put("minecraft:soul_soil", 52);
        blockIndexMap.put("minecraft:cyan_wool", 53);
        blockIndexMap.put("minecraft:sculk", 54);
        blockIndexMap.put("minecraft:ancient_debris", 55);
        blockIndexMap.put("minecraft:waxed_cut_copper", 56);
        blockIndexMap.put("minecraft:waxed_exposed_cut_copper", 57);
        blockIndexMap.put("minecraft:waxed_copper_block", 58);
        blockIndexMap.put("minecraft:waxed_cut_copper", 59);
        blockIndexMap.put("minecraft:copper_ore", 60);
        blockIndexMap.put("minecraft:waxed_oxidized_copper", 61);
        blockIndexMap.put("minecraft:diamond_block", 62);
        blockIndexMap.put("minecraft:diamond_ore", 63);
        blockIndexMap.put("minecraft:yellow_terracotta", 64);
        blockIndexMap.put("minecraft:orange_terracotta", 65);
        blockIndexMap.put("minecraft:red_terracotta", 66);
        blockIndexMap.put("minecraft:brown_terracotta", 67);
        blockIndexMap.put("minecraft:white_concrete", 68);
        blockIndexMap.put("minecraft:light_gray_concrete", 69);
        blockIndexMap.put("minecraft:gray_concrete", 70);
        blockIndexMap.put("minecraft:black_concrete", 71);
        blockIndexMap.put("minecraft:stripped_spruce_log", 72);
        blockIndexMap.put("minecraft:bamboo_planks", 73);
        blockIndexMap.put("minecraft:bamboo_block", 74);
        blockIndexMap.put("minecraft:stripped_bamboo_block", 75);
        blockIndexMap.put("minecraft:tinted_glass", 76);
        blockIndexMap.put("minecraft:cherry_log", 77);
        blockIndexMap.put("minecraft:iron_bars", 78);
        blockIndexMap.put("minecraft:mud_bricks", 79);
        blockIndexMap.put("minecraft:emerald_block", 80);
        blockIndexMap.put("minecraft:emerald_ore", 81);
        blockIndexMap.put("minecraft:lapis_block", 82);
        blockIndexMap.put("minecraft:lapis_ore", 83);
        blockIndexMap.put("minecraft:purple_glazed_terracotta", 84);
        blockIndexMap.put("minecraft:magenta_glazed_terracotta", 85);
        blockIndexMap.put("minecraft:cyan_glazed_terracotta", 86);
        blockIndexMap.put("minecraft:blue_glazed_terracotta", 87);
        blockIndexMap.put("minecraft:ochre_froglight", 88);
        blockIndexMap.put("minecraft:glowstone", 89);
        blockIndexMap.put("minecraft:verdant_froglight", 90);
        blockIndexMap.put("minecraft:crying_obsidian", 91);
        blockIndexMap.put("minecraft:white_stained_glass", 92);
        blockIndexMap.put("minecraft:netherite_block", 93);
        blockIndexMap.put("minecraft:beacon", 94);
        blockIndexMap.put("minecraft:pink_wool", 95);
        blockIndexMap.put("minecraft:dripstone_block", 96);
        blockIndexMap.put("minecraft:dead_tube_coral_block", 97);
        blockIndexMap.put("minecraft:magenta_concrete", 98);
        blockIndexMap.put("minecraft:soul_lantern", 99);
        blockIndexMap.put("minecraft:shulker_box", 100);
        blockIndexMap.put("minecraft:deepslate_emerald_ore", 101);
        blockIndexMap.put("minecraft:reinforced_deepslate", 102);
        blockIndexMap.put("minecraft:polished_blackstone", 103);
        blockIndexMap.put("minecraft:sandstone", 104);
        blockIndexMap.put("minecraft:orange_concrete", 105);
        blockIndexMap.put("minecraft:red_sandstone", 106);
        blockIndexMap.put("minecraft:chiseled_quartz_block", 107);
        blockIndexMap.put("minecraft:bamboo_mosaic", 108);
        blockIndexMap.put("minecraft:crimson_stem", 109);
        blockIndexMap.put("minecraft:acacia_log", 110);
        blockIndexMap.put("minecraft:warped_stem", 111);
        blockIndexMap.put("minecraft:prismarine_bricks", 112);
        blockIndexMap.put("minecraft:lodestone", 113);
        blockIndexMap.put("minecraft:raw_iron_block", 114);
        blockIndexMap.put("minecraft:crafting_table", 115);
        blockIndexMap.put("minecraft:crimson_hyphae", 116);
        blockIndexMap.put("minecraft:warped_hyphae", 117);
        blockIndexMap.put("minecraft:honeycomb_block", 118);
        blockIndexMap.put("minecraft:glass", 119);
        blockIndexMap.put("minecraft:polished_andesite", 120);
        blockIndexMap.put("minecraft:lime_wool", 121);
        blockIndexMap.put("minecraft:dark_prismarine", 122);
        blockIndexMap.put("minecraft:birch_log", 123);
        blockIndexMap.put("minecraft:polished_blackstone_bricks", 124);
        blockIndexMap.put("minecraft:iron_trapdoor", 125);
        blockIndexMap.put("minecraft:gilded_blackstone", 126);
        blockIndexMap.put("minecraft:tuff", 127);
        blockIndexMap.put("minecraft:sandstone", 128);
        BLOCK_TO_GM_INSTRUMENT = Collections.unmodifiableMap(blockIndexMap);
        GM_INSTRUMENT_TO_BLOCK = Collections.unmodifiableMap(
                blockIndexMap.entrySet().stream()
                        .collect(Collectors.toMap(Map.Entry::getValue, Map.Entry::getKey)));
    }
    public static final Map<Integer, String> GM_INSTRUMENT_ID_TO_NAME;
    static {
        Map<Integer, String> map = new HashMap<>();
        map.put(0, "Acoustic Grand Piano");
        map.put(1, "Bright Acoustic Piano");
        map.put(2, "Electric Grand Piano");
        map.put(3, "Honky-tonk Piano");
        map.put(4, "Electric Piano 1");
        map.put(5, "Electric Piano 2");
        map.put(6, "Harpsichord");
        map.put(7, "Clavinet");
        map.put(8, "Celesta");
        map.put(9, "Glockenspiel");
        map.put(10, "Music Box");
        map.put(11, "Vibraphone");
        map.put(12, "Marimba");
        map.put(13, "Xylophone");
        map.put(14, "Tubular Bells");
        map.put(15, "Dulcimer");
        map.put(16, "Drawbar Organ");
        map.put(17, "Percussive Organ");
        map.put(18, "Rock Organ");
        map.put(19, "Church Organ");
        map.put(20, "Reed Organ");
        map.put(21, "Accordion");
        map.put(22, "Harmonica");
        map.put(23, "Tango Accordion");
        map.put(24, "Acoustic Guitar (nylon)");
        map.put(25, "Acoustic Guitar (steel)");
        map.put(26, "Electric Guitar (jazz)");
        map.put(27, "Electric Guitar (clean)");
        map.put(28, "Electric Guitar (muted)");
        map.put(29, "Overdriven Guitar");
        map.put(30, "Distortion Guitar");
        map.put(31, "Guitar Harmonics");
        map.put(32, "Acoustic Bass");
        map.put(33, "Electric Bass (finger)");
        map.put(34, "Electric Bass (pick)");
        map.put(35, "Fretless Bass");
        map.put(36, "Slap Bass 1");
        map.put(37, "Slap Bass 2");
        map.put(38, "Synth Bass 1");
        map.put(39, "Synth Bass 2");
        map.put(40, "Violin");
        map.put(41, "Viola");
        map.put(42, "Cello");
        map.put(43, "Contrabass");
        map.put(44, "Tremolo Strings");
        map.put(45, "Pizzicato Strings");
        map.put(46, "Orchestral Harp");
        map.put(47, "Timpani");
        map.put(48, "String Ensemble 1");
        map.put(49, "String Ensemble 2");
        map.put(50, "Synth Strings 1");
        map.put(51, "Synth Strings 2");
        map.put(52, "Choir Aahs");
        map.put(53, "Voice Oohs");
        map.put(54, "Synth Voice");
        map.put(55, "Orchestra Hit");
        map.put(56, "Trumpet");
        map.put(57, "Trombone");
        map.put(58, "Tuba");
        map.put(59, "Muted Trumpet");
        map.put(60, "French Horn");
        map.put(61, "Brass Section");
        map.put(62, "Synth Brass 1");
        map.put(63, "Synth Brass 2");
        map.put(64, "Soprano Sax");
        map.put(65, "Alto Sax");
        map.put(66, "Tenor Sax");
        map.put(67, "Baritone Sax");
        map.put(68, "Oboe");
        map.put(69, "English Horn");
        map.put(70, "Bassoon");
        map.put(71, "Clarinet");
        map.put(72, "Piccolo");
        map.put(73, "Flute");
        map.put(74, "Recorder");
        map.put(75, "Pan Flute");
        map.put(76, "Blown Bottle");
        map.put(77, "Shakuhachi");
        map.put(78, "Whistle");
        map.put(79, "Ocarina");
        map.put(80, "Lead 1 (square)");
        map.put(81, "Lead 2 (sawtooth)");
        map.put(82, "Lead 3 (calliope)");
        map.put(83, "Lead 4 (chiff)");
        map.put(84, "Lead 5 (charang)");
        map.put(85, "Lead 6 (voice)");
        map.put(86, "Lead 7 (fifths)");
        map.put(87, "Lead 8 (bass + lead)");
        map.put(88, "Pad 1 (new age)");
        map.put(89, "Pad 2 (warm)");
        map.put(90, "Pad 3 (polysynth)");
        map.put(91, "Pad 4 (choir)");
        map.put(92, "Pad 5 (bowed)");
        map.put(93, "Pad 6 (metallic)");
        map.put(94, "Pad 7 (halo)");
        map.put(95, "Pad 8 (sweep)");
        map.put(96, "FX 1 (rain)");
        map.put(97, "FX 2 (soundtrack)");
        map.put(98, "FX 3 (crystal)");
        map.put(99, "FX 4 (atmosphere)");
        map.put(100, "FX 5 (brightness)");
        map.put(101, "FX 6 (goblins)");
        map.put(102, "FX 7 (echoes)");
        map.put(103, "FX 8 (sci-fi)");
        map.put(104, "Sitar");
        map.put(105, "Banjo");
        map.put(106, "Shamisen");
        map.put(107, "Koto");
        map.put(108, "Kalimba");
        map.put(109, "Bag Pipe");
        map.put(110, "Fiddle");
        map.put(111, "Shanai");
        map.put(112, "Tinkle Bell");
        map.put(113, "Agogo");
        map.put(114, "Steel Drums");
        map.put(115, "Woodblock");
        map.put(116, "Taiko Drum");
        map.put(117, "Melodic Tom");
        map.put(118, "Synth Drum");
        map.put(119, "Reverse Cymbal");
        map.put(120, "Guitar Fret Noise");
        map.put(121, "Breath Noise");
        map.put(122, "Seashore");
        map.put(123, "Bird Tweet");
        map.put(124, "Telephone Ring");
        map.put(125, "Helicopter");
        map.put(126, "Applause");
        map.put(127, "Gunshot");
        map.put(128, "Standard Drum Kit");
        GM_INSTRUMENT_ID_TO_NAME = Collections.unmodifiableMap(map);
    }
}